In [9]:
import warnings
warnings.filterwarnings("ignore")

In [11]:
pd.set_option("display.max_columns",None)

In [1]:
import pandas as pd

In [3]:
data=pd.read_excel(r"C:\Users\Nandani\Downloads\Home_prediction_mock.xlsx")

In [4]:
data.shape

(34857, 21)

In [5]:
print(data.dtypes)

Suburb                   object
Address                  object
Rooms                     int64
Type                     object
Price                   float64
Method                   object
SellerG                  object
Date             datetime64[ns]
Distance                float64
Postcode                float64
Bedroom2                float64
Bathroom                float64
Car                     float64
Landsize                float64
BuildingArea            float64
YearBuilt               float64
CouncilArea              object
Lattitude               float64
Longtitude              float64
Regionname               object
Propertycount           float64
dtype: object

In [12]:
data.head(5)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,2016-09-03,2.5,3067.0,2.0,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,2016-12-03,2.5,3067.0,2.0,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,2016-02-04,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,2016-02-04,2.5,3067.0,3.0,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.8114,145.0116,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,2017-03-04,2.5,3067.0,3.0,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.8093,144.9944,Northern Metropolitan,4019.0

In [7]:
data.isnull().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
YearBuilt        19306
CouncilArea          3
Lattitude         7976
Longtitude        7976
Regionname           3
Propertycount        3
dtype: int64

In [8]:
(data.isnull().sum()/len(data))*100

Suburb            0.000000
Address           0.000000
Rooms             0.000000
Type              0.000000
Price            21.832057
Method            0.000000
SellerG           0.000000
Date              0.000000
Distance          0.002869
Postcode          0.002869
Bedroom2         23.573457
Bathroom         23.599277
Car              25.039447
Landsize         33.881286
BuildingArea     60.576068
YearBuilt        55.386293
CouncilArea       0.008607
Lattitude        22.882061
Longtitude       22.882061
Regionname        0.008607
Propertycount     0.008607
dtype: float64

Fill missing values:

Numerical columns → median

Categorical columns → mode

Price             7610 n  Bedroom2          8217 n
Bathroom          8226 n
Car               8728 n
Landsize         11810 n
BuildingArea     21115 n
YearBuilt        19306 n
CouncilArea          3 c
Lattitude         7976 n
Longtitude        7976 n
Regionname           3 c
Propertycount        3 n

In [13]:
data.head(3)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,2016-09-03,2.5,3067.0,2.0,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,2016-12-03,2.5,3067.0,2.0,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,2016-02-04,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,Northern Metropolitan,4019.0

In [39]:
data["Distance"]=data["Distance"].fillna(data["Distance"].median())

In [40]:
data["Postcode"]=data["Postcode"].fillna(data["Postcode"].median())

In [14]:
data["Price"]=data["Price"].fillna(data["Price"].median())

In [15]:
data["Bedroom2"]=data["Bedroom2"].fillna(data["Bedroom2"].median())

In [16]:
data["Bathroom"]=data["Bathroom"].fillna(data["Bathroom"].median())

In [17]:
data["Car"]=data["Car"].fillna(data["Car"].median())

In [18]:
data["Landsize"]=data["Landsize"].fillna(data["Landsize"].median())

In [19]:
data["BuildingArea"]=data["BuildingArea"].fillna(data["BuildingArea"].median())

In [20]:
data["YearBuilt"]=data["YearBuilt"].fillna(data["YearBuilt"].median())

In [21]:
data["Lattitude"]=data["Lattitude"].fillna(data["Lattitude"].median())

In [22]:
data["Longtitude"]=data["Longtitude"].fillna(data["Longtitude"].median())

In [23]:
data["Propertycount"]=data["Propertycount"].fillna(data["Propertycount"].median())

In [33]:
data["CouncilArea"]=data["CouncilArea"].fillna(data["CouncilArea"].mode()[0])

In [32]:
data["Regionname"]=data["Regionname"].fillna(data["Regionname"].mode()[0])

In [26]:
data["YearBuilt"].unique()

array([1970., 1900., 2014., 2006., 1910., 2009., 1860., 1890., 1925.,
       2005., 2010., 1880., 1985., 2013., 2012., 1920., 1950., 1998.,
       1930., 2016., 1965., 1960., 1980., 2011., 2015., 1975., 1993.,
       2003., 1995., 1996., 2000., 1990., 1915., 2004., 2008., 1916.,
       1962., 1955., 1988., 1953., 1997., 2007., 1967., 1964., 1889.,
       1888., 1934., 1966., 1935., 1969., 1940., 1938., 1887., 1904.,
       1972., 1978., 1939., 1945., 1927., 1948., 1947., 1968., 1958.,
       2017., 1999., 1992., 1961., 1928., 1977., 1919., 1976., 2001.,
       1926., 1981., 1986., 1943., 1974., 1956., 1936., 1957., 1987.,
       2002., 1952., 1994., 1949., 1905., 1912., 1924., 1885., 1923.,
       1918., 1991., 1942., 1973., 2018., 1982., 2106., 1971., 1963.,
       1931., 1897., 1906., 1883., 1989., 1983., 1937., 1903., 1913.,
       1830., 1895., 1908., 1917., 1902., 1854., 1850., 1898., 1941.,
       1951., 1946., 1984., 1901., 1921., 1929., 1959., 1979., 1892.,
       1933., 1911., 1886., 1876., 1907., 1881., 1870., 1932., 1875.,
       1863., 1893., 1856., 1877., 1894., 1857., 1914., 1868., 1884.,
       1872., 1954., 1922., 1896., 1800., 1909., 1196., 1891., 1862.,
       1871., 1899., 1820., 1869., 1855., 2019., 1879.])

Q4

Remove duplicate rows.

In [29]:
data.duplicated().sum()

np.int64(1)

In [34]:
data.drop_duplicates(inplace=True)

In [35]:
data.duplicated().sum()

np.int64(0)

In [37]:
data.shape

(34856, 21)

In [41]:
data.isnull().sum()

Suburb           0
Address          0
Rooms            0
Type             0
Price            0
Method           0
SellerG          0
Date             0
Distance         0
Postcode         0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
YearBuilt        0
CouncilArea      0
Lattitude        0
Longtitude       0
Regionname       0
Propertycount    0
dtype: int64

Clean text columns:
Remove leading/trailing spaces
Convert to Title Case
Check unique values

In [61]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34856 entries, 0 to 34856
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         34856 non-null  object
 1   Address        34856 non-null  object
 2   Rooms          34856 non-null  int64
 3   Type           34856 non-null  object
 4   Price          34856 non-null  float64
 5   Method         34856 non-null  object
 6   SellerG        34852 non-null  object
 7   Date           34856 non-null  datetime64[ns]
 8   Distance       34856 non-null  float64
 9   Postcode       34856 non-null  float64
 10  Bedroom2       34856 non-null  float64
 11  Bathroom       34856 non-null  float64
 12  Car            34856 non-null  float64
 13  Landsize       34856 non-null  float64
 14  BuildingArea   34856 non-null  float64
 15  YearBuilt      34856 non-null  float64
 16  CouncilArea    34856 non-null  object
 17  Lattitude      34856 non-null  float64
 18  Longtitude     34856 non-null  float64
 19  Regionname     34856 non-null  object
 20  Propertycount  34856 non-null  float64
dtypes: datetime64[ns](1), float64(12), int64(1), object(7)
memory usage: 5.9+ MB

 Suburb           object        
 Address          object
 Type             object
Method          object        
 SellerG        object
CouncilArea      object
 Regionname       object

In [44]:
data["Suburb"]=data["Suburb"].str.strip().str.title()

In [45]:
data["Address"]=data["Address"].str.strip().str.title()

In [46]:
data["Type"]=data["Type"].str.strip().str.title()

In [47]:
data["Method"]=data["Method"].str.strip().str.title()

In [48]:
data["SellerG"]=data["SellerG"].str.strip().str.title()

In [49]:
data["CouncilArea"]=data["CouncilArea"].str.strip().str.title()

In [50]:
data["Regionname"]=data["Regionname"].str.strip().str.title()

In [51]:
data["Suburb"].unique()

array(['Abbotsford', 'Airport West', 'Albert Park', 'Alphington',
       'Altona', 'Altona North', 'Armadale', 'Ascot Vale', 'Ashburton',
       'Ashwood', 'Avondale Heights', 'Balaclava', 'Balwyn',
       'Balwyn North', 'Bentleigh', 'Bentleigh East', 'Box Hill',
       'Braybrook', 'Brighton', 'Brighton East', 'Brunswick',
       'Brunswick West', 'Bulleen', 'Burwood', 'Camberwell', 'Canterbury',
       'Carlton North', 'Carnegie', 'Caulfield', 'Caulfield North',
       'Caulfield South', 'Chadstone', 'Clifton Hill', 'Coburg',
       'Coburg North', 'Collingwood', 'Doncaster', 'Eaglemont',
       'Elsternwick', 'Elwood', 'Essendon', 'Essendon North', 'Fairfield',
       'Fitzroy', 'Fitzroy North', 'Flemington', 'Footscray', 'Glen Iris',
       'Glenroy', 'Gowanbrae', 'Hadfield', 'Hampton', 'Hampton East',
       'Hawthorn', 'Heidelberg Heights', 'Heidelberg West', 'Hughesdale',
       'Ivanhoe', 'Kealba', 'Keilor East', 'Kensington', 'Kew',
       'Kew East', 'Kooyong', 'Maidstone', 'Malvern', 'Malvern East',
       'Maribyrnong', 'Melbourne', 'Middle Park', 'Mont Albert',
       'Moonee Ponds', 'Moorabbin', 'Newport', 'Niddrie',
       'North Melbourne', 'Northcote', 'Oak Park', 'Oakleigh South',
       'Parkville', 'Pascoe Vale', 'Port Melbourne', 'Prahran', 'Preston',
       'Reservoir', 'Richmond', 'Rosanna', 'Seddon', 'South Melbourne',
       'South Yarra', 'Southbank', 'Spotswood', 'St Kilda', 'Strathmore',
       'Sunshine', 'Sunshine North', 'Sunshine West', 'Surrey Hills',
       'Templestowe Lower', 'Thornbury', 'Toorak', 'Viewbank', 'Watsonia',
       'West Melbourne', 'Williamstown', 'Williamstown North', 'Windsor',
       'Yallambie', 'Yarraville', 'Aberfeldie', 'Bellfield',
       'Brunswick East', 'Burnley', 'Campbellfield', 'Carlton',
       'East Melbourne', 'Essendon West', 'Fawkner', 'Hawthorn East',
       'Heidelberg', 'Ivanhoe East', 'Jacana', 'Kingsbury', 'Kingsville',
       'Murrumbeena', 'Ormond', 'West Footscray', 'Albion', 'Brooklyn',
       'Glen Huntly', 'Oakleigh', 'Ripponlea', 'Cremorne', 'Docklands',
       'South Kingsville', 'Strathmore Heights', 'Travancore',
       'Caulfield East', 'Seaholme', 'Keilor Park', 'Gardenvale',
       'Princes Hill', 'Altona Meadows', 'Ardeer', 'Attwood', 'Bayswater',
       'Bayswater North', 'Beaumaris', 'Berwick', 'Blackburn',
       'Blackburn South', 'Boronia', 'Briar Hill', 'Broadmeadows',
       'Bundoora', 'Burnside Heights', 'Burwood East', 'Cairnlea',
       'Caroline Springs', 'Cheltenham', 'Clarinda', 'Clayton',
       'Clyde North', 'Craigieburn', 'Cranbourne', 'Croydon',
       'Croydon Hills', 'Croydon North', 'Dandenong', 'Dandenong North',
       'Diamond Creek', 'Dingley Village', 'Doncaster East', 'Donvale',
       'Doreen', 'Edithvale', 'Eltham', 'Eltham North', 'Emerald',
       'Epping', 'Eumemmerring', 'Ferntree Gully', 'Forest Hill',
       'Frankston', 'Frankston North', 'Frankston South', 'Gisborne',
       'Gladstone Park', 'Glen Waverley', 'Greensborough', 'Greenvale',
       'Hallam', 'Healesville', 'Heathmont', 'Highett', 'Hillside',
       'Hoppers Crossing', 'Huntingdale', 'Keilor Downs', 'Keilor Lodge',
       'Keysborough', 'Kings Park', 'Lalor', 'Lower Plenty', 'Lynbrook',
       'Macleod', 'Melton', 'Melton South', 'Melton West', 'Mentone',
       'Mernda', 'Mickleham', 'Mill Park', 'Mitcham', 'Montmorency',
       'Montrose', 'Mordialloc', 'Mount Waverley', 'Mulgrave',
       'Narre Warren', 'Noble Park', 'Nunawading', 'Oakleigh East',
       'Parkdale', 'Point Cook', 'Ringwood', 'Ringwood East', 'Rockbank',
       'Rowville', 'Roxburgh Park', 'Sandringham', 'Seabrook', 'Seaford',
       'Skye', 'South Morang', 'Springvale', 'Springvale South',
       'St Albans', 'St Helena', 'Sunbury', 'Sydenham', 'Tarneit',
       'Taylors Hill', 'Taylors Lakes', 'Tecoma', 'Templestowe',
       'The Basin', 'Thomastown', 'Truganina', 'Tullamarine', 'Vermont',
       'Vermont South', 'Wantirna', 'Wantirna South', 'Werribee',
       'Werribee South', 'Westmeadows', 'Williams Landing', 'Wollert',
       'Wyndham Vale', 'Aspendale', 'Black Rock', 'Blackburn North',
       'Bonbeach', 'Carrum', 'Chelsea', 'Clayton South', 'Dallas',
       'Delahey', 'Doveton', 'Mckinnon', 'Mooroolbark', 'Pakenham',
       'Ringwood North', 'Scoresby', 'Warrandyte', 'Watsonia North',
       'Wattle Glen', 'Wheelers Hill', 'Albanvale', 'Aspendale Gardens',
       'Belgrave', 'Carrum Downs', 'Cranbourne East', 'Cranbourne North',
       'Deer Park', 'Heatherton', 'Kilsyth', 'Langwarrin', 'Notting Hill',
       'Patterson Lakes', 'Riddells Creek', 'Beaconsfield Upper',
       'Chelsea Heights', 'Chirnside Park', 'Coolaroo', 'Darley',
       'Hampton Park', 'Keilor', 'Meadow Heights', 'Mount Evelyn',
       'North Warrandyte', 'Sandhurst', 'Silvan', 'Wallan',
       'Croydon South', 'Derrimut', 'Diggers Rest', 'Knoxfield', 'Upwey',
       'Warranwood', 'Bacchus Marsh', 'Bullengarook', 'Deepdene',
       'Hurstbridge', 'Kurunjang', 'Laverton', 'Lilydale', 'Wonga Park',
       'Endeavour Hills', 'Officer', 'Olinda', 'Waterways',
       'Beaconsfield', 'Yarra Glen', 'Brookfield', 'Lysterfield',
       'Plenty', 'Whittlesea', 'Burnside', 'New Gisborne', 'Guys Hill',
       'Plumpton', 'Monbulk', 'Avonsleigh', 'Wildwood', 'Gisborne South',
       'Research', 'Botanic Ridge', 'Bulla', 'Coldstream',
       'Hopetoun Park', 'Cranbourne West', 'Eynesbury', 'Fawkner Lot',
       'Ferny Creek', 'Wandin North', 'Kalkallo', 'Menzies Creek'],
      dtype=object)

In [ ]:
 Suburb           object        
 Address          object
 Type             object
Method          object        
 SellerG        object
CouncilArea      object
 Regionname       object

In [54]:
data["Address"].unique()

array(['68 Studley St', '85 Turner St', '25 Bloomburg St', ...,
       '147A Severn St', '12/37 Stephen St', '3 Tarrengower St'],
      dtype=object)

In [55]:
data["Type"].unique()

array(['H', 'U', 'T'], dtype=object)

In [56]:
data["Method"].unique()

array(['Ss', 'S', 'Vb', 'Sp', 'Pi', 'Sn', 'W', 'Pn', 'Sa'], dtype=object)

In [57]:
data["SellerG"].unique()

array(['Jellis', 'Biggin', 'Rounds', 'Nelson', 'Collins', 'Dingle',
       'Purplebricks', 'Greg', 'Philip', 'Little', 'Kay', 'Beller',
       'Marshall', 'Hockingstuart', 'Brad', 'Maddison', 'Barry',
       'Airport', 'Considine', 'Rendina', 'Ray', 'Propertyau', 'Mcdonald',
       'Frank', 'Prof.', 'Harcourts', 'Thomson', 'Buxton', 'Rt',
       "Sotheby'S", 'Cayzer', 'Chisholm', 'Mcgrath', 'Brace', 'Miles',
       'Holland', 'Love', 'Thomas', 'Barlow', 'Sweeney', 'Village', 'Jas',
       'Williams', 'Gunn&Co', 'Burnham', 'Point', 'Compton', 'Fn',
       'Hunter', 'Raine&Horne', 'Noel', 'Hodges', 'Gary', 'Fletchers',
       'Woodards', 'Raine', 'Alexkarbon', 'Walshe', 'Weda', 'Stockdale',
       'Tim', 'Buxton/Marshall', 'Aime', 'Moonee', 'Har', 'Edward', 'Rw',
       'North', 'Micm', 'Ascend', 'Christopher', 'Morrison', 'Bekdon',
       'Mandy', 'R&H', 'Fletchers/One', 'Lindellas', 'Appleby', 'Assisi',
       'One', 'Owen', 'Parkes', 'C21', 'Century', "O'Brien", 'Bayside',
       'Anderson', 'Paul', 'Hockingstuart/Buxton', 'Smart', 'First',
       'Matthew', 'Melbourne', 'Nick', 'Allens', 'Bells', 'Nguyen',
       'Trimson', 'Douglas', 'Batty', 'Gl', 'Ypa', "Tiernan'S", 'J',
       'Castran', 'Branon', 'Rodney', 'Joseph', 'Harrington', 'Galldon',
       'Grantham', 'Chambers', 'Pagan', 'Peter',
       'Hockingstuart/Advantage', 'Ross', 'Rayner', 'Garvey',
       "O'Donoghues", 'Hamilton', 'Weast', 'Kelly', 'Property',
       "Private/Tiernan'S", 'Australian', 'Bustin', "Abercromby'S",
       'Whiting', 'Itrak', 'Del', 'Caine', 'Nicholson', 'Jmre', 'Asl',
       'Changing', 'Re', 'Walsh', 'Foxtons', 'Ham', 'Darren', 'Vic',
       'Haughton', 'Scott', 'Pride', 'Morleys', 'Wilson',
       'Buxton/Advantage', 'Professionals', 'Joe', 'Red',
       'Hockingstuart/Jellis', 'Craig', 'Naison', 'Sweeney/Advantage',
       'Reach', 'Domain', 'Eview', 'Jason', "D'Aprano", 'Charlton',
       'Wood', 'William', 'Coventry', 'Buckingham', 'Nardella', 'Karen',
       'Lj', 'Shape', 'Direct', 'Fletchers/Fletchers', 'Besser',
       'Johnston', 'Avion', 'Redina', 'Clairmont', 'Lucas', 'Dixon',
       'Xynergy', 'Elite', 'Buxton/Find', 'W.B.', 'Leased',
       'Harcourts/Barry', 'Win', 'Collings', 'New', 'Parkinson', 'Geoff',
       'Hockingstuart/Barry', 'Blue', 'Msm', 'Steveway',
       'Hockingstuart/Village', 'Vicprop', 'Inner', 'Meadows', 'Allan',
       'S&L', 'Crane', 'Calder', 'Metro', 'Homes', 'Zahn', 'Mason',
       'Landfield', 'David', 'Luxe', 'Prowse', 'Ken', 'Rombotis', 'Ione',
       'Hockingstuart/Sweeney', 'Iconek', 'Luxton', 'Hooper', 'Jrw',
       'Oak', 'White', 'Jim', 'Weston', '@Realty', 'Reed', 'Oriental',
       'Max', 'Steller', 'Rosin', 'Real', 'Jeffrey', 'Hall', 'Icon',
       'Buymyplace', 'Whitefox', 'Christou', 'Marvelli', "Grant'S",
       'Hoskins', 'Gardiner', 'Mclennan', 'Triwest', 'Reliance',
       'Prdnationwide', 'Only', 'Leyton', 'Isell', 'Obrien', 'Maitland',
       'Millership', 'L', 'Emerson', 'Follett', 'Ash', 'Llc', 'Ace',
       'Flannagan', 'Carter', 'Wesell', 'M.J', 'Iproperty',
       'Hayeswinckle', 'Schroeder', 'Ihomes', 'Remax', 'Space', 'Victory',
       'Aumeca', 'Mindacom', 'Ryder', 'Sanctuary', 'Leeburn', 'Asset',
       'Westside', 'Sell', 'Mitchell', 'Darras', 'U', 'Nicholas',
       'Rexhepi', 'Keatings', 'Aquire', 'Conquest', 'Prime', 'Donovan',
       'Community', 'Free', 'Veitch', 'John', 'Peake', 'Ristic', 'Jy',
       'Upper', 'Daniel', 'Vichomes', nan, 'Mcnaughton', 'Leading',
       'Bullen', 'Better', 'Boutique', 'Royston', 'Langwell', 'Silver',
       'Wyndham', 'Kaye', 'Nicholls', 'Bowman', 'Just', 'Home', 'Le',
       'Cooper', 'Black', 'The', 'Open', 'Roger', 'Mcewing', 'Sandhurst',
       'Boran', 'Hockingstuart/Hockingstuart', 'Area', 'Mj', 'Eric', 'Sn',
       'Waterfront', 'P', 'Prd', 'Bombay', 'Quinta', 'T', 'Tanner', 'Ljh',
       'Munn', 'Knight', 'Justin', 'Blackbird', 'Sweeney/Burnham', 'H',
       'Alex', 'Can', 'Pavilion', 'Benchmark', 'Gellibrand',
       'Hockingstuart/Harcourts', 'Charter', 'Surreal', 'A', 'Upside',
       'Meallin', 'Malvern', 'Mark', 'Bradly', 'For', 'Peninsula',
       'Sutherland', 'Leaders', 'Spencer', 'Mcgrath/Langwell', 'Benlor',
       'Burns', 'Sterling', 'K.R.Peters', 'Buxton/Buxton', 'Carlinsmith',
       'Gold', 'Hill', 'People', 'Hockingstuart/Biggin', 'Mega', 'Skad',
       'Ruralco', 'Create', 'Janice', 'R', 'G&H', 'Commercial', 'Psp',
       'Hockingstuart/Cayzer', 'Unity', 'Sprint', 'Mcgrath/Buxton',
       'Hockingstuart/Marshall', 'Mcgrath/First', 'Voglwalpole',
       'Watermark', 'Methven'], dtype=object)

In [58]:
data["CouncilArea"].unique()

array(['Yarra City Council', 'Moonee Valley City Council',
       'Port Phillip City Council', 'Darebin City Council',
       'Hobsons Bay City Council', 'Stonnington City Council',
       'Boroondara City Council', 'Monash City Council',
       'Glen Eira City Council', 'Whitehorse City Council',
       'Maribyrnong City Council', 'Bayside City Council',
       'Moreland City Council', 'Manningham City Council',
       'Melbourne City Council', 'Banyule City Council',
       'Brimbank City Council', 'Kingston City Council',
       'Hume City Council', 'Knox City Council', 'Maroondah City Council',
       'Casey City Council', 'Melton City Council',
       'Greater Dandenong City Council', 'Nillumbik Shire Council',
       'Cardinia Shire Council', 'Whittlesea City Council',
       'Frankston City Council', 'Macedon Ranges Shire Council',
       'Yarra Ranges Shire Council', 'Wyndham City Council',
       'Moorabool Shire Council', 'Mitchell Shire Council'], dtype=object)

In [59]:
data["Regionname"].unique()

array(['Northern Metropolitan', 'Western Metropolitan',
       'Southern Metropolitan', 'Eastern Metropolitan',
       'South-Eastern Metropolitan', 'Eastern Victoria',
       'Northern Victoria', 'Western Victoria'], dtype=object)

Fix data types:
Year_Built → int
Price → float
Bedrooms & Bathrooms → int

In [62]:
data["YearBuilt"]=data["YearBuilt"].astype(int)

In [63]:
data["Price"]=data["Price"].astype(float)

In [66]:
data["Bedroom2"]=data["Bedroom2"].astype(int)

In [67]:
data["Bathroom"]=data["Bathroom"].astype(int)

In [68]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34856 entries, 0 to 34856
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         34856 non-null  object
 1   Address        34856 non-null  object
 2   Rooms          34856 non-null  int64
 3   Type           34856 non-null  object
 4   Price          34856 non-null  float64
 5   Method         34856 non-null  object
 6   SellerG        34852 non-null  object
 7   Date           34856 non-null  datetime64[ns]
 8   Distance       34856 non-null  float64
 9   Postcode       34856 non-null  float64
 10  Bedroom2       34856 non-null  int64
 11  Bathroom       34856 non-null  int64
 12  Car            34856 non-null  float64
 13  Landsize       34856 non-null  float64
 14  BuildingArea   34856 non-null  float64
 15  YearBuilt      34856 non-null  int64
 16  CouncilArea    34856 non-null  object
 17  Lattitude      34856 non-null  float64
 18  Longtitude     34856 non-null  float64
 19  Regionname     34856 non-null  object
 20  Propertycount  34856 non-null  float64
dtypes: datetime64[ns](1), float64(9), int64(4), object(7)
memory usage: 5.9+ MB

Remove logically incorrect records:
Bedrooms ≤ 0
Bathrooms ≤ 0
Sqft ≤ 0
Price ≤ 0

In [69]:
data["Bedroom2"].unique()

array([ 2,  3,  4,  6,  1,  5,  7,  0,  8,  9, 30, 20, 10, 16, 12])

In [70]:
data=data[(data["Bedroom2"]>0) & (data["Bathroom"]>0) & (data["Price"]>0)]

Standardize column names:
Lowercase
Replace spaces with underscore

In [80]:
data.columns=data.columns.str.lower().str.replace(" ","_")

In [81]:
data.shape

(34800, 21)

In [82]:
data.isnull().sum()

suburb           0
address          0
rooms            0
type             0
price            0
method           0
sellerg          4
date             0
distance         0
postcode         0
bedroom2         0
bathroom         0
car              0
landsize         0
buildingarea     0
yearbuilt        0
councilarea      0
lattitude        0
longtitude       0
regionname       0
propertycount    0
dtype: int64

In [83]:
data.duplicated().sum()

np.int64(0)

In [84]:
data.describe()

,rooms,price,date,distance,postcode,bedroom2,bathroom,car,landsize,buildingarea,yearbuilt,lattitude,longtitude,propertycount
count,34800.000000,3.480000e+04,34800,34800.000000,34800.000000,34800.000000,34800.000000,34800.000000,34800.000000,34800.000000,34800.000000,34800.000000,34800.000000,34800.000000
mean,3.031552,1.010988e+06,2017-05-23 20:04:45.517241600,11.190095,3116.076293,3.066753,1.715632,1.799195,569.438966,145.574841,1967.894339,-37.809917,145.003200,7572.788017
min,1.000000,8.500000e+04,2016-01-28 00:00:00,0.000000,3000.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1196.000000,-38.190430,144.423790,83.000000
25%,2.000000,6.950000e+05,2016-11-27 00:00:00,6.400000,3051.000000,3.000000,1.000000,1.000000,358.000000,136.000000,1970.000000,-37.846890,144.964400,4385.000000
50%,3.000000,8.700000e+05,2017-07-08 00:00:00,10.300000,3103.000000,3.000000,2.000000,2.000000,521.000000,136.000000,1970.000000,-37.807600,145.007800,6763.000000
75%,4.000000,1.150000e+06,2017-10-28 00:00:00,14.000000,3156.000000,3.000000,2.000000,2.000000,598.000000,136.000000,1970.000000,-37.770857,145.051750,10412.000000
max,16.000000,1.120000e+07,2018-03-17 00:00:00,48.100000,3978.000000,30.000000,12.000000,26.000000,433014.000000,44515.000000,2106.000000,-37.390200,145.526350,21650.000000
std,0.970044,5.722451e+05,NaN,6.791759,109.085692,0.855554,0.650162,0.881214,2766.111330,252.427596,25.057494,0.079319,0.105607,4427.796060

In [85]:
data.columns

Index(['suburb', 'address', 'rooms', 'type', 'price', 'method', 'sellerg',
       'date', 'distance', 'postcode', 'bedroom2', 'bathroom', 'car',
       'landsize', 'buildingarea', 'yearbuilt', 'councilarea', 'lattitude',
       'longtitude', 'regionname', 'propertycount'],
      dtype='object')

In [87]:
data['property_id'] = range(1, len(data)+1)

In [88]:
data[['property_id',
'suburb','address','rooms','type',
'distance','postcode','bedroom2','bathroom','car','landsize','buildingarea',
'yearbuilt','councilarea','lattitude',
'longtitude','regionname','propertycount']].to_csv("Property_Info.csv", index=False)

data[['property_id','price','method','sellerg','date']].to_csv("Sales_Info.csv", index=False)

data.to_csv("house_prediction_clean.csv",index=False)